### ISSUE TITLE
Don't work private song settings

### ISSUE THREAD

**Issue by senechal-ua** [SoftProjector/softprojector#2]
![2017-03-25 4 32 23](https://cloud.githubusercontent.com/assets/25769334/24323069/bdad8894-1178-11e7-824e-c3200aa26af6.png)

When I change and save the private song settings, they are not applied when the song is displayed on the screen

**Comment by vladozar** [comment]
Fixed with this commit https://github.com/SoftProjector/softprojector/commit/31bc6250a3fb9d5a5ed87d0962edc6c5d392d9ec
