### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by randomuser101** [SoftProjector/softprojector#32]
There is a spelling mistake on the "Delete Bible?" window of the manage database tab. It states, "This action will *permanentrly* delete this Bible" 
![mistake](https://user-images.githubusercontent.com/40478625/41752974-bbf6ce90-7598-11e8-9ec7-ec90b00dd6db.PNG)

**Comment by a1ip** [comment]
Also "Alingment:" and "Inalid Numeric Value" mistakes found.

**Comment by vladozar** [comment]
The word _permanentrly_ been fixed in this Pull Request https://github.com/SoftProjector/softprojector/pull/42

**Comment by vladozar** [comment]
All other spelling mistakes will be fixed under this issue https://github.com/SoftProjector/softprojector/issues/41
