### ISSUE TITLE
SoftProjector 2.1 - Song Book Delay

### ISSUE THREAD

**Issue by rvkuzmik** [SoftProjector/softprojector#37]
Currently the song book has a really big delay, about 3 times slower than what SoftProjector 1 had. On version 2.1 the bible part switches really quickly and works perfect but the song book just takes a really long time, you have to switch the verse like 1-1.5 seconds before the verse ends.

**Comment by senechal-ua** [comment]
In my case, this problem was due to a very large font. Try to reduce the font of the lyrics.
The font size for songs is now slightly larger than the font size of the  Bible verse with the same values ​​in the settings.

**Comment by rvkuzmik** [comment]
That's the interesting part... We use the same font size in SP1 and it worked perfectly.. I would go in and check out the code myself but I think i'll wait and see maybe one if the devs will give some insight.

Smaller font will defeat the purpose of our newly installed LED Panel Wall. But I will try it out in the next couple days and see if that'll help!
