### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by randomuser101** [SoftProjector/softprojector#41]
I've opened another issue over a year ago but since it hasn't been addressed yet I'm opening a more detailed one.  The Show button has an obvious spelling mistake, "Dsiplay to screen (F4)." This can be found in the softprojector.ui file on line 592. 

There is another set of mistakes in the manage database widget. When you try to delete something, the resulting dialog box says "This action will premanentrly delete this bible/songbook/theme."
This is found in managedatadialog.cpp on lines 796, 1132, 1809. 

These are just small spelling mistakes and if I find more I will update this post.

**Comment by zhskyy** [comment]
thanks
fixed in [pull request](https://github.com/SoftProjector/softprojector/pull/42)

**Comment by andrewr-rak** [comment]
When is the next update? It's been years...

**Comment by andrewr-rak** [comment]
Hi. Are you referring to the Dark theme for the operators Bible? If so, the
newest release (2.2) would be great.

**Comment by zhskyy** [comment]
I created a Win build and You may find it here https://github.com/zhskyy/softprojector/releases/tag/v2.2.1
The macOS build will be later.

It contains a bug withes only. 
About new features. I don't sure should  I do it, maybe @vladozar will do it but I have not any communication with him. Now I try to fix known issues only.

**Comment by vladozar** [comment]
Few other spelling issues from Issue #32 :
Also "Alingment:" and "Inalid Numeric Value" mistakes found.

**Comment by vladozar** [comment]
This pull request https://github.com/SoftProjector/softprojector/pull/47 fixes the issued mentioned above. 
If you wish to, please review it. I will be merging it in a few days.
