### ISSUE TITLE
Media play after complet/exit audio start playing again

### ISSUE THREAD

**Issue by Dmitrix83** [SoftProjector/softprojector#52]
When viewing video file and let it finish with last frame fixed on display. Press escape to exit media view, audio of the video will start playing in the background again.  To stop it need to press play then pause button to stop it.

Some what cool if you do not press play/pause. for those who do not use backgrounds image for Bible or Song book the video is visible when viewing Bible verse or song. 
Frame switching is slow in this mode even if you are not using fade effect or shadow.

**Comment by vladozar** [comment]
Thanks for the video bug. I will take a look into it.
