### ISSUE TITLE
Text getting cut off

### ISSUE THREAD

**Issue by MaxKam** [SoftProjector/softprojector#9]
When running the latest code, I'm seeing an issue where the secondary and tertiary Bible translations are getting cut off on some verses. Two examples below. 

![gen1-2](https://user-images.githubusercontent.com/13650720/29246343-a4d72c3e-7fab-11e7-9156-6f9294bba329.PNG)
![isaiah 66-11](https://user-images.githubusercontent.com/13650720/29246344-a7031fa4-7fab-11e7-97f4-ae35c4bad305.PNG)

As you can see the English verses don't finish. This happens no matter what translation is set as the secondary or tertiary versions. 
This issue only happens with some verses. I haven't been able to figure out specifically what causes this as there are much longer verses that appear just fine. 

When I set the height manually for the "m_bdSets.ptRect" rectangle in imagegenerator.cpp, the verses all display correctly. Code examples below.

**Original code:**
```
377. if(haveSecondary && !m_verse.secondary_text.isEmpty())
378.    {
379.        painter->drawText(left,m_bdSets.stRect.top(),w,m_bdSets.ptRect.height(), tflags, m_verse.secondary_text);
380.    }
```
**Manually setting height:**
```
377. if(haveSecondary && !m_verse.secondary_text.isEmpty())
378.    {
379.        painter->drawText(left,m_bdSets.stRect.top(),w, 800, tflags, m_verse.secondary_text);
380.    }
```

**Comment by vladozar** [comment]
The issue has been fixed. 

I'm not sure which source you were using, but if the latest, it had a simple copy-paste bug. It was fixed with this commit: https://github.com/SoftProjector/softprojector/pull/11/commits/194aeca715c31bd03b7c4e9d1bfb0a709e0752b5
